# Generated by Django 4.0.3 on 2022-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baqhdad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArabicLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNumber', models.CharField(max_length=50, verbose_name='رقم الوثيقة')),
                ('dDate', models.DateField(verbose_name='تاريخ الوثيقة')),
                ('dTitle', models.CharField(max_length=300, verbose_name='عنوان الوثيقة')),
                ('dName', models.CharField(max_length=300, verbose_name='اسم الطالبة')),
                ('dYear_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('dDepartment', models.CharField(default='قسم اللغة العربية', max_length=300, verbose_name='القسم')),
                ('dNote', models.CharField(blank=True, max_length=300, null=True, verbose_name='الملاحظات')),
                ('dImg', models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/ArabicLan/%y', verbose_name='صورة الوثيقة')),
            ],
            options={
                'verbose_name': 'قسم اللغة العربية',
                'verbose_name_plural': 'قسم اللغة العربية',
            },
        ),
        migrations.CreateModel(
            name='FinanceBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNumber', models.CharField(max_length=50, verbose_name='رقم الوثيقة')),
                ('dDate', models.DateField(verbose_name='تاريخ الوثيقة')),
                ('dTitle', models.CharField(max_length=300, verbose_name='عنوان الوثيقة')),
                ('dName', models.CharField(max_length=300, verbose_name='اسم الطالبة')),
                ('dYear_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('dDepartment', models.CharField(default='قسم المالية والمصرفية', max_length=300, verbose_name='القسم')),
                ('dNote', models.CharField(blank=True, max_length=300, null=True, verbose_name='الملاحظات')),
                ('dImg', models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/Fiqh/%y', verbose_name='صورة الوثيقة')),
            ],
            options={
                'verbose_name': 'قسم المالية والمصرفية',
                'verbose_name_plural': 'قسم المالية والمصرفية',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNumber', models.CharField(max_length=50, verbose_name='رقم الوثيقة')),
                ('dDate', models.DateField(verbose_name='تاريخ الوثيقة')),
                ('dTitle', models.CharField(max_length=300, verbose_name='عنوان الوثيقة')),
                ('dName', models.CharField(max_length=300, verbose_name='اسم الطالبة')),
                ('dYear_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('dDepartment', models.CharField(default='قسم التاريخ-بغداد', max_length=300, verbose_name='القسم')),
                ('dNote', models.CharField(blank=True, max_length=300, null=True, verbose_name='الملاحظات')),
                ('dImg', models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/History/%y', verbose_name='صورة الوثيقة')),
            ],
            options={
                'verbose_name': 'قسم التاريخ',
                'verbose_name_plural': 'قسم التاريخ',
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNumber', models.CharField(max_length=50, verbose_name='رقم الوثيقة')),
                ('dDate', models.DateField(verbose_name='تاريخ الوثيقة')),
                ('dTitle', models.CharField(max_length=300, verbose_name='عنوان الوثيقة')),
                ('dName', models.CharField(max_length=300, verbose_name='اسم الطالبة')),
                ('dYear_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('dDepartment', models.CharField(default='قسم القانون-بغداد', max_length=300, verbose_name='القسم')),
                ('dNote', models.CharField(blank=True, max_length=300, null=True, verbose_name='الملاحظات')),
                ('dImg', models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/Law/%y', verbose_name='صورة الوثيقة')),
            ],
            options={
                'verbose_name': 'قسم القانون',
                'verbose_name_plural': 'قسم القانون',
            },
        ),
        migrations.AlterField(
            model_name='asol_aldeen_boys',
            name='dImg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/Asol-Boys/%y', verbose_name='صورة الوثيقة'),
        ),
        migrations.AlterField(
            model_name='asol_aldeen_girls',
            name='dImg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/Asol-Girls/%y', verbose_name='صورة الوثيقة'),
        ),
        migrations.AlterField(
            model_name='english',
            name='dImg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/EN/%y', verbose_name='صورة الوثيقة'),
        ),
        migrations.AlterField(
            model_name='fiqhfound',
            name='dImg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Baqhdad/Fiqh/%y', verbose_name='صورة الوثيقة'),
        ),
    ]
