# Generated by Django 4.0.3 on 2022-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asol_ALdeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNumber', models.CharField(max_length=50, verbose_name='رقم الوثيقة')),
                ('dDate', models.DateField(verbose_name='تاريخ الوثيقة')),
                ('dTitle', models.CharField(max_length=300, verbose_name='عنوان الوثيقة')),
                ('dName', models.CharField(max_length=300, verbose_name='اسم الطالب')),
                ('dYear_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('dDepartment', models.CharField(default='اصول الدين/ديالى', max_length=300, verbose_name='القسم')),
                ('dNote', models.CharField(max_length=300, verbose_name='الملاحظات')),
                ('dImg', models.ImageField(upload_to='photos/Dyala/%y/%m/%d')),
            ],
        ),
    ]
